### ISSUE TITLE
Destructive Effect

### ISSUE THREAD

**Issue by llothos** [Chaithi/genesysMagicCalculator#4]
Noticed this on the spell builder for the Destructive Effect.

Your text: Attack gains Sunder quality. Also gains **Pierce 1**.

Book Text: The attack gains the Sunder quality. The attack also gains the Pierce quality with a rating **equal to the character's
ranks in Knowledge.**

**Comment by Chaithi** [comment]
Hello @llothos

This is actually intended. If you update your characteristics at the top (specifically the Knowledge stat), it will update Destructive (and many others) to match your stat.

**Comment by llothos** [comment]
ah OK, :), never played with characteristics at all when I was looking at it. Just noticed the wording was different. Thanks
